sinonimo(abundante,mucho).
sinonimo(acabar,terminar).
sinonimo(finalizar,terminar).
sinonimo(advertir,notar).
sinonimo(alterado,nervioso).
sinonimo(altura,elevación).
sinonimo(amplificar,agrandar).
sinonimo(angustia,malestar).
sinonimo(anteojos,gafas).
sinonimo(apto,hábil).
sinonimo(armonía,calma).
sinonimo(avaro,amarrete).
sinonimo(barato,económico).
sinonimo(batalla,guerra).
sinonimo(bobo,necio).
sinonimo(boleto,billete).
sinonimo(bonito,hermoso).
sinonimo(cabello,pelo).
sinonimo(cálido,caliente).
sinonimo(calmar,atenuar).
sinonimo(cama,lecho).
sinonimo(camino,sendero).
sinonimo(cantina,bar).
sinonimo(castigar,sancionar).
sinonimo(cola,rabo).
sinonimo(combate,contienda).
sinonimo(cómodo,confortable).
sinonimo(comprar,adquirir).
sinonimo(comprender,entender).
sinonimo(constitución,estatuto).
sinonimo(crear,inventar).
sinonimo(cumbre,cima).
sinonimo(dadivoso,desprendido).
sinonimo(danzar,bailar).
sinonimo(decir,pronunciar).
sinonimo(defecto,imperfección).
sinonimo(demente,loco).
sinonimo(desobediente,indisciplinado).
sinonimo(destruir,eliminar).
sinonimo(dicha,alegría).
sinonimo(ebrio,borracho).
sinonimo(economizar,ahorrar).
sinonimo(edén,paraíso).
sinonimo(educar,enseñar).
sinonimo(elegir,escoger).
sinonimo(elevar,subir).
sinonimo(embrujar,hechizar).
sinonimo(embuste,mentira).
sinonimo(enfurecer,enojar).
sinonimo(enigma,incógnita).
sinonimo(enseñanza,educación).
sinonimo(entero,completo).
sinonimo(escrito,nota).
sinonimo(escuchar,atender).
sinonimo(estudiante,alumno).
sinonimo(expresar,exponer).
sinonimo(extraño,raro).
sinonimo(fácil,sencillo).
sinonimo(fallecer,morir).
sinonimo(famoso,célebre).
sinonimo(fiel,leal).
sinonimo(flaco,delgado).
sinonimo(flecha,saeta).
sinonimo(formación,instrucción).
sinonimo(fotografía,retrato).
sinonimo(fragmento,pedazo).
sinonimo(frizar,congelar).
sinonimo(garaje,cochera).
sinonimo(generoso,dadivoso).
sinonimo(gigante,enorme).
sinonimo(gordo,obeso).
sinonimo(humildad,modestia).
sinonimo(humo,humareda).
sinonimo(idéntico,igual).
sinonimo(idioma,lengua).
sinonimo(iluminar,alumbrar).
sinonimo(importe,valor).
sinonimo(increíble,impresionante).
sinonimo(indicio,pista).
sinonimo(insolencia,arrogancia).
sinonimo(insulto,agravio).
sinonimo(inteligencia,sabiduría).
sinonimo(invariabilidad,uniformidad).
sinonimo(junta,delegación).
sinonimo(labor,trabajo).
sinonimo(lanzar,arrojar).
sinonimo(llano,plano).
sinonimo(lucha,pelea).
sinonimo(maestro,profesor).
sinonimo(magnate,poderoso).
sinonimo(magnífico,espléndido).
sinonimo(matar,asesinar).
sinonimo(matrimonio,boda).
sinonimo(miedo,pánico).
sinonimo(misericordia,piedad).
sinonimo(momento,instante).
sinonimo(monarca,rey).
sinonimo(montar,cabalgar).
sinonimo(naipe,baraja).
sinonimo(nombrar,designar).
sinonimo(norma,regla).
sinonimo(nunca,jamás).
sinonimo(oir,escuchar).
sinonimo(óleo,aceite).
sinonimo(orar,rezar).
sinonimo(página,hoja).
sinonimo(parar,detener).
sinonimo(partir,dividir).
sinonimo(paz,tranquilidad).
sinonimo(pedagogía,enseñanza).
sinonimo(pelo,cabello).
sinonimo(penunmbra,tinieblas).
sinonimo(plano,llano).
sinonimo(poco,escaso).
sinonimo(posible,factible).
sinonimo(preocupación,inquietud).
sinonimo(previo,anterior).
sinonimo(profundo,hondo).
sinonimo(queja,lamento).
sinonimo(querer,pretender).
sinonimo(raro,extraño).
sinonimo(razón,motivo).
sinonimo(reposo,quietud).
sinonimo(robar,hurtar).
sinonimo(rostro,cara).
sinonimo(saber,conocer).
sinonimo(sabio,erudito).
sinonimo(sabroso,rico).
sinonimo(sanar,curar).
sinonimo(sano,saludable).
sinonimo(satisfacer,saciar).
sinonimo(silbar,pitar).
sinonimo(silueta,contorno).
sinonimo(soberbia,altanería).
sinonimo(sombra,oscuridad).
sinonimo(sumar,agregar).
sinonimo(tacaño,avaro).
sinonimo(tomar,beber).
sinonimo(transcribir,manuscribir).
sinonimo(triunfo,victoria).
sinonimo(valiente,aventurado).
sinonimo(valioso,preciado).
sinonimo(veloz,rápido).
sinonimo(vereda,senda).
sinonimo(vivir,habitar).
sinonimo(volver,regresar).
sinonimo_de(X,Y):-sinonimo(X,Y);sinonimo(Y,X).
